### ISSUE TITLE
Handling favicons

### ISSUE THREAD

**Issue by PragmaTechSydney** [hugo-sid/hugo-blog-awesome#1]
Hey Sid, awesome work on this template! I was wondering what the best way is to handle favicons, is that something you've already built in? Thanks, Phil

**Comment by hugo-sid** [comment]
Hi @PragmaTechSydney . Thanks for liking my work.

As of now, support for favicons is not there. But I am planning to add it soon (possibly today).

Please don't forget to star the repo, if you liked the Hugo theme.

**Comment by PragmaTechSydney** [comment]
Thanks Sid - starred and watched!

Couple of other features I was planning to try and figure out myself, just thought you might be interested:

- ability to add Flickr and Mastodon icon links to the footer (without white lines appearing between each icon)
- ability to create links that open in new tab (target="blank")

**Comment by PragmaTechSydney** [comment]
Oh and Google Analytics support :-)

**Comment by hugo-sid** [comment]
@PragmaTechSydney , thanks for starring the repo. 

Those are some interesting features that we can consider adding to the theme.

- [ ] Add favicons support

**Comment by hugo-sid** [comment]
Hi @PragmaTechSydney, I have added support for favicons.

You can find the relevant documentation [here](https://github.com/hugo-sid/hugo-blog-awesome#adding-favicon).

**Comment by hugo-sid** [comment]
Added support for Google Analytics. Docs available [here](https://github.com/hugo-sid/hugo-blog-awesome/blob/f5a07184be533763b5818f462f1a87e60a97facc/exampleSite/config.toml#L6).

**Comment by PragmaTechSydney** [comment]
Many thanks, much appreciated!

**Comment by hugo-sid** [comment]
You are welcome @PragmaTechSydney.
