### ISSUE TITLE
RSS feed issue

### ISSUE THREAD

**Issue by chettyarun** [hugo-sid/hugo-blog-awesome#109]
**Describe the bug**
When viewed in an RSS reader, only the first few lines of the posts are shown. Rest of the content isn't visible (checked with multiple RSS readers. Checked with multiple example sites using this theme)

**Steps to reproduce**
1. Go to any RSS reader and check the site which is using this theme
2. Go to any of the posts and see that only first few lines are displayed

**Expected behavior**
The entire post's content should be visible on the RSS reader

**Screenshots**
<img width="1435" alt="image" src="https://github.com/hugo-sid/hugo-blog-awesome/assets/1394688/83b4390b-26b5-4d26-9549-4536a02c4159">
The screenshot is from Feedly RSS reader using the theme's demo page as an example. Only the first few lines are shown

**Comment by hugo-sid** [comment]
Thanks for reporting this issue @chettyarun. I will have a look at it.

**Comment by chettyarun** [comment]
I tried going through the issue. Couldn't figure out what was wrong. I couldn't find any RSS limits set by default. And, there wasn't any particular setting in the TOML file either. 

Anyway I can help close this issue? I also tried adding a new RSS xml file to the layouts folder but that didn't work.

**Comment by hugo-sid** [comment]
Hi @chettyarun, the default RSS template in Hugo produces a description of the article and no the whole article.

Aren't most sites have their RSS configured this way?

**Comment by chettyarun** [comment]
Most sites actually pull in the entire article @hugo-sid. I checked with one random hugo theme and found that it also is pulling a description of the article and not the entire article. 

But, generally all blogs out there pull the entire article. Anyway you think this can be fixed?

**Comment by hugo-sid** [comment]
@chettyarun, I have added support for putting entire article in RSS feed.

You have to set `rssFeedDescription="full"` in `config.toml` file. You can take a look at the following code, which illustrates this further.


https://github.com/hugo-sid/hugo-blog-awesome/blob/aa7630b4295384b3ecddb14f826dbd1ab1535c52/exampleSite/config.toml#L71-L74

Please update your Hugo theme to use this feature. Feel free to reopen this issue, in case you encounter something unexpected.
