### ISSUE TITLE
Long inline code does not break line

### ISSUE THREAD

**Issue by jnkn6** [hugo-sid/hugo-blog-awesome#133]
**Describe the bug**

**Steps to reproduce**
Write long inline code

**Expected behavior**
If inline code is long, it should break line.

**Screenshots**
![image](https://github.com/hugo-sid/hugo-blog-awesome/assets/72091653/a00d57de-2763-47eb-a51c-62e9fd3eb63a)

Thank you!

**Comment by hugo-sid** [comment]
Thanks for reporting.

A question came to my mind. Why not use block level code:
````
```
long code
```
````
instead of inline code?

**Comment by jnkn6** [comment]
I'm using both codeblock and inline code.

I use codeblock when writing multiple line of codes, and I use inline code to quote to explain specific one line of code.
