### ISSUE TITLE
On the homepage, post dates wrap if post titles are too long

### ISSUE THREAD

**Issue by fmaida** [hugo-sid/hugo-blog-awesome#136]
**Describe the bug**
On the homepage, post dates wrap if post titles are too long. This happens especially if the post titles are too long and you're browsing the website from a device with a small screen resolution - such as a mobile phone.

**Steps to reproduce**
1. Create a new post or edit an existing one with a very long title
2. See the homepage in a web browser
3. Collapse the browser window to the minimum, or open the website on a mobile phone for example

This is an example of what I get. Please notice that post date wraps to the second line of text:

![Home___Awesome_Hugo_blog-4](https://github.com/hugo-sid/hugo-blog-awesome/assets/605017/c7f495d6-2d2d-4a46-9584-031e79060644)

**How I fixed this problem**

**I know this is not an elegant solution**, but at the moment it's working.
I simply patched the source in `layouts/partials/postCard.html` by replacing this code:

```go
<time class="post-item-meta" datetime="{{ dateFormat $ISO_date .Date }}">
    {{ time.Format $configDateFormat .Date }}
</time>
```

with this code that replaces normal spaces with non-breakable spaces:

```go
<time class="post-item-meta" datetime="{{ dateFormat $ISO_date .Date }}">
    {{ $postDate := time.Format $configDateFormat .Date }}
    {{ strings.Replace $postDate " " "&nbsp;" | safeHTML }}
</time>
```

And now this is how the posts are now displayed on a single line:

![Home___Awesome_Hugo_blog-3](https://github.com/hugo-sid/hugo-blog-awesome/assets/605017/a77714df-cec6-420e-a1bc-fc7f8dddf181)

You see, it's not the best solution in the world, so I was hoping that maybe you could find a better solution to this problem.

Best regards

**Comment by hugo-sid** [comment]
@fmaida, thanks for reporting the bug.

> You see, it's not the best solution in the world, so I was hoping that maybe you could find a better solution to this problem.

You're right. I will see if there is a better way to do this.

**Comment by LautaroLobo12** [comment]
max len and ... ? it may be worth a try to see how it looks

**Comment by fmaida** [comment]
up

**Comment by hugo-sid** [comment]
@fmaida can you please confirm whether this issue is resolved by this [commit](https://github.com/hugo-sid/hugo-blog-awesome/commit/b8b4753e4db009a59ed81616c2a127b10243d8b8) ?

**Comment by fmaida** [comment]
I tested it on both Chrome device emulation and on my real iPhone 12 Pro.
It works like a charm now, thank you very much.
