### ISSUE TITLE
RSS Template Errors Preventing Build

### ISSUE THREAD

**Issue by nibl** [hugo-sid/hugo-blog-awesome#141]
RSS template fails with multiple errors:

... render of "home" failed: ".../themes/hugo-blog-awesome/layouts/_default/rss.xml:22:17": execute of template failed: template: _default/rss.xml:22:17: executing "_default/rss.xml" at <site>: can't evaluate field LanguageCode in type *langs.Language

Hugo gives the same error for render of "taxonomy" and "term". The errors do not occur with  version 1.2.0 of the theme, which is the only older version I have tested.

Theme is latest version pulled via git. Hugo is v0.111, the latest available on Ubuntu via Snap.

**Comment by the-chronomancer** [comment]
Same exact issue here with no clear fix. Would love to use this template but unfortunately cannot.

**Comment by hugo-sid** [comment]
Thanks @nibl, @the-chronomancer & @InSpaceDude  for reporting this.

I don't see any error with the latest version of Hugo. See the screenshot below for more details.

![image](https://github.com/hugo-sid/hugo-blog-awesome/assets/122173059/5f648864-bf4b-44ed-b6a4-a659eeec214c)

**Comment by paddy-exe** [comment]
@hugo-sid I am encountering this issue now as well:
It doesn't appear when building locally but using the hugo action doesn't work anymore to publish the changes
<img width="1044" alt="image" src="https://github.com/hugo-sid/hugo-blog-awesome/assets/38077837/a87cb505-a81c-4ffe-8fc4-1bb4def877b6">

**Comment by paddy-exe** [comment]
Alright after a LOOONG look at it again, I solved it now. It doesn't work with the GitHub Action because the action uses an older version of hugo.

@nibl @the-chronomancer Make sure you have hugo set to the latest version:
```yml
jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.120.4
```

I had mine before on `HUGO_VERSION: 0.111.2`

**Comment by hugo-sid** [comment]
> Make sure you have hugo set to the latest version:

Thanks @paddy-exe for confirming that this issue doesn't exist on Hugo (v0.120.4).

I'm closing this issue for now. Please feel free to reopen/comment if anyone encounters this issue again.
