### ISSUE TITLE
Toggle light/dark doesn't work with web server

### ISSUE THREAD

**Issue by ColinMaudry** [hugo-sid/hugo-blog-awesome#17]
**Describe the bug**

I have checked #16 and my baseUrl is fine :)

The toggle works when I run the blog with `hugo server`.

It doesn't when I generate the static files with `hugo` and run the site with an HTTP server (nginx or [http-server node module](https://www.npmjs.com/package/http-server)).

I could reproduce with the example site.

My website is deployed here: https://colin.cafe/#

The source code is here: https://github.com/ColinMaudry/colin.cafe

```
hugo version
hugo v0.111.3-5d4eb5154e1fed125ca8e9b5a0315c4180dab192+extended linux/amd64 BuildDate=2023-03-12T11:40:50Z VendorInfo=snap:0.111.3
```
**Steps to reproduce**

```
cd colin.cafe
hugo
cd public
http-server
```

**Expected behavior**

When clicking on the sun icon the theme should switch to dark.

**Device information (please complete the following information):**

 - OS: Ubuntu 22.10
 - Browser
   - Firefox 111.0.1
   - Vivaldi 5.7.2921.65

**Comment by ColinMaudry** [comment]
[Thanks](https://Ko-fi.com/home/coffeeshop?txid=8fe573e1-ed8c-48fc-b50c-30cbced24169&mode=public&img=ogiboughtsomeone) for working on it ☕

**Comment by hugo-sid** [comment]
Hi Colin. Thanks for supporting my work.

When I clone your repo locally, the problem vanishes (see the screen recording below).

But when I use, GitHub codespace to develop/test, the problem appears.

This is strange.

https://user-images.githubusercontent.com/122173059/228923610-6939c902-b867-48d4-a93b-54cb227ca9dd.mp4

**Comment by hugo-sid** [comment]
Where is https://colin.cafe/ hosted?

**Comment by hugo-sid** [comment]
Hi @ColinMaudry . It's a small mistake, but took a lot of time to debug. 😄

The problem is that `[params]` is missing in your `config.toml`.

This is your `config.toml`:

https://github.com/ColinMaudry/colin.cafe/blob/1bc8a7983040a3cc09c8ec2c0970135bb4daf429/config.toml#L17-L27

This is the `config.toml` from the theme's `exampleSite`:

https://github.com/hugo-sid/hugo-blog-awesome/blob/ce9f89bda93816cc284561c9e4a5e30d389b830a/exampleSite/config.toml#L34-L43

**Comment by hugo-sid** [comment]
On a side note, I was wondering why in the above comment, the lines referenced from the theme's `config.toml` are displayed in a nice code snippet where as lines referenced from your repo are not.

I navigated to [GitHub docs,](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-a-permanent-link-to-a-code-snippet) where it is mentioned that: 

"This type of permanent link will render as a code snippet only in the repository it originated in. In other repositories, the permalink code snippet will render as a URL."

**Comment by eddygta17** [comment]
I had the same issue. For me it was solved when I fixed the domain from:
`baseURL = <final domain I planned to use>`
to
`baseURL = <the domain I am currently using for testing>`

**Comment by ColinMaudry** [comment]
It did, thanks!
