### ISSUE TITLE
Date on post is not following dateFormat

### ISSUE THREAD

**Issue by matrixik** [hugo-sid/hugo-blog-awesome#177]
**Describe the bug**
dateFormat from config is not implemented everywhere

**Steps to reproduce**
1. Set `dateFormat = "2006-01-02"`
2. Open posts page (all dates in `2006-01-02` format)
3. Open any post
4. Date is in `2 Jan 2006` format

**Expected behavior**
Dates everywhere in `2006-01-02` format

**Screenshots**
![Screenshot from 2024-03-11 15-26-43](https://github.com/hugo-sid/hugo-blog-awesome/assets/201930/d1ff6906-88f8-4240-b3f4-f2ec62629ca7)
![Screenshot from 2024-03-11 15-27-21](https://github.com/hugo-sid/hugo-blog-awesome/assets/201930/42672e6e-17d0-4ded-8a72-49bd6e8e09dc)

**Device information**
 - Browser firefox
 - Version 04b8dfd

**Additional context**

**Comment by hugo-sid** [comment]
Hello @matrixik. Thanks for reporting this issue.

This issue has been resolved in the [v1.17.0 release](https://github.com/hugo-sid/hugo-blog-awesome/releases/tag/v1.17.0).

Feel free to reopen this issue, if the problem persists.

**Comment by matrixik** [comment]
Great. Thank you.
