### ISSUE TITLE
Home button (icon looks like house) is not working properly.

### ISSUE THREAD

**Issue by Rayjun0525** [hugo-sid/hugo-blog-awesome#36]
Hello :)
There is a problem of going to the top of the git page when you press the home button. I wonder if this is my git page setting problem or if it can be solved by setting it in the config.toml file.

**Comment by hugo-sid** [comment]
Hello :)

>There is a problem of going to the top of the git page when you press the home button. I wonder if this is my git page setting problem or if it can be solved by setting it in the config.toml file.

Could you please explain what you meant by 'git page' ?

**Comment by Rayjun0525** [comment]
I am writing a hugoblog through the page of GitHub.
My url is like this
https://gitId.github.io/blogTitle/

However, clicking the Home button on the main page will switch to page 404 of github.
The same problem occurs when you click 'See all posts' on the main page that is set to go to /posts/.

I resolved by changing the link address of the third line of the file "hugo-blog-awesome/layouts/partials/header.html" and the link address of the 20th line of the file "hugo-blog-awesome/layouts/index.html"

But to avoid this problem, can't we change it so that we can specify the initial home path as a variable? I am not familiar with the correction of hugo yet, so I inquired about the issue instead of a commit request.

**Comment by hugo-sid** [comment]
Thanks for reporting this issue @Rayjun0525 . It has been fixed now.

> can't we change it so that we can specify the initial home path as a variable

Yes, we can do that.

Can you update your theme and then set the `baseURL` in `config.toml` file to your blog/website URL?

**Comment by Rayjun0525** [comment]
It's **Fantastic**. Thank you for the quick action!

**Comment by hugo-sid** [comment]
You are welcome @Rayjun0525.

Happy blogging :)

**Comment by kusyka911** [comment]
> set the `baseURL` in `config.toml`
@hugo-sid @Rayjun0525 
Sorry for reopening this issue.
But I want to mention that there is ability to set baseURL variable in build command (hugo -b /kusyka/). Setting baseURL in config file may break dev server (`hugo server` command)

**Comment by hugo-sid** [comment]
>Setting baseURL in config file may break site ruining on dev server

@kusyka911, my experience has been quite the opposite of what you mentioned.

I have worked with a ton of Hugo websites but I never experienced this issue. If this issue arises only when we use no-root baseURL, then I have nothing to say. I have not used a non-root baseURL yet.

**Comment by Ritter99** [comment]
Hello, I am having a similar issue where the Home Icon Button is redirecting me to "localhost:1313". 

I have double checked that my config file has baseURL set to my blog's domain. Is there something else I should check as well?

**Comment by hugo-sid** [comment]
> Hello, I am having a similar issue where the Home Icon Button is redirecting me to "localhost:1313".
> 
> I have double checked that my config file has baseURL set to my blog's domain. Is there something else I should check as well?

Hi @Ritter99, can you please answer the following questions?

- What command are you using to deploy or build your site?
- What exactly is your `baseURL` ?

**Comment by Ritter99** [comment]
@hugo-sid, I am using the "server" command to run Hugo and my `baseURL = "https://blog.example.com/"`

**Comment by Jiaaming** [comment]
> [@hugo-sid](https://github.com/hugo-sid), I am using the "server" command to run Hugo and my `baseURL = "https://blog.example.com/"`

Hi, I got the same issue. Do you still remember how you solved it?

**Comment by kuzand** [comment]
> [@hugo-sid](https://github.com/hugo-sid), I am using the "server" command to run Hugo and my `baseURL = "https://blog.example.com/"`

You should use `hugo server` only for local testing.. For deployment builds, use `hugo` so that it embeds into html your baseUrl and not localhost.
