### ISSUE TITLE
Image and Emoji support + "Link 1" issue

### ISSUE THREAD

**Issue by paddy-exe** [hugo-sid/hugo-blog-awesome#4]
Hey there, I have been using your template for my blog website: https://paddy-exe.github.io

Thank you for creating this :D

I have found several issues:
1. `enableEmoji: true` in the md header does NOT actually activate Emoji support. Not really sure why
2. I have no idea where I can put images to embed into the .md files. I have tried `static`, a post package folder with an `img` subfolder and none worked
3. In the template, there is no way to change the "Link 1" and "Link 2" links except to go into the template itself and change it. Is this intended?

**Comment by hugo-sid** [comment]
Hi Patrick.

> I have been using your template for my blog website: https://paddy-exe.github.io/

I'm glad to know that my theme has been useful for you. Thanks for choosing this theme.

> Thank you for creating this :D

You're welcome Patrick.

> I have found several issues

Thanks for identifying these issues. Here is what I have to say as of now:
1. Emoji issue - I am able to reproduce this. will implement a fix.
2. Putting images - I have not yet used images in the example or sample posts (in the `exampleSite` folder. I will update you when I do this.
3. No way to change the links except to go into the template - no Patrick, it's not intended to be that way. I will implement a more elegant solution where links can be managed in the `config.toml` file.

**Comment by paddy-exe** [comment]
> 1. Emoji issue - I am able to reproduce this. will implement a fix.
> 2. Putting images - I have not yet used images in the example or sample posts (in the `exampleSite` folder. I will update you when I do this.
> 3. No way to change the links except to go into the template - no Patrick, it's not intended to be that way. I will implement a more elegant solution where links can be managed in the `config.toml` file.

Thanks for the quick reply! Looking forward to the fixes!

**Comment by hugo-sid** [comment]
Hi Patrick. 

1. The emoji issue has been solved.
2. The links in the footer can now be managed using `config.toml`.

      Here is a sample configuration:
      
      https://github.com/hugo-sid/hugo-blog-awesome/blob/main/exampleSite/config.toml#L49-L59
      
      You can see the result of this below.
      
      ![image](https://user-images.githubusercontent.com/122173059/224822550-87477c87-99eb-4da4-b0d0-0bd6f448a127.png)
      
      I feel, this is an elegant solution to manage links in the footer. What do you say ?

**Comment by paddy-exe** [comment]
> Hi Patrick.
> 
> 1. The emoji issue has been solved.
> 2. The links in the footer can now be managed using `config.toml`.
>    Here is a sample configuration:
>    https://github.com/hugo-sid/hugo-blog-awesome/blob/b9fbdad8b3949b0672226387d18873c415597de9/exampleSite/config.toml#L49-L59
>    
>    You can see the result of this below.
>    ![image](https://user-images.githubusercontent.com/122173059/224822550-87477c87-99eb-4da4-b0d0-0bd6f448a127.png)
>    I feel, this is an elegant solution to manage links in the footer. What do you say ?

This is a very elegant solution! Thank you :D Btw where does this retrieve the icons from? Would be good to refer to the source of the icons (if they are not made by you) so ppl can check if another name like e.g. Mastodon or Ko-Fi is supported

**Comment by hugo-sid** [comment]
> This is a very elegant solution! Thank you :D

You are welcome Patrick.

You are correct regarding names of icons. How does someone figure out the icons that he can use ?
I made it clear by adding documentation [here]( https://github.com/hugo-sid/hugo-blog-awesome#adding-social-icons).

**Comment by hugo-sid** [comment]
I have modified the `exampleSite/content` folder to make it more suitable to include images. You can check it out [this post](https://github.com/hugo-sid/hugo-blog-awesome/blob/main/exampleSite/content/posts/markdown-syntax/index.md).

**Comment by paddy-exe** [comment]
> I have modified the `exampleSite/content` folder to make it more suitable to include images. You can check it out in [this post](https://github.com/hugo-sid/hugo-blog-awesome/blob/main/exampleSite/content/posts/markdown-syntax/index.md).

Amazing work! Thank you very much :D I assume this also means that gifs are also supported?

**Comment by hugo-sid** [comment]
> Amazing work! Thank you very much :D

You are welcome Patrick. Thanks for pointing out the issues.

> I assume this also means that gifs are also supported?

Yes.

> Also, do the files inside the folders have to be named index.md or is that irrelevant?

The markdown file has to be named `index.md`. For more information you can read about leaf bundles on the Hugo documentation website [here](https://gohugo.io/content-management/page-bundles/#leaf-bundles). There is no restriction on naming of other files or resources.

**Comment by paddy-exe** [comment]
Perfect. Since all the issues are solved now, I will close this issue here now.
