### ISSUE TITLE
homepage title bug

### ISSUE THREAD

**Issue by jerry011235** [hugo-sid/hugo-blog-awesome#45]
**Describe the bug**
The homepage title seems to be duplicated.

**Steps to reproduce**
What I did：
1. install hugo.
2. run the following command:
```
hugo new site myblog
cd myblog
```
Get the latest version of the theme:
```
git clone --depth=1 https://github.com/hugo-sid/hugo-blog-awesome.git themes/hugo-blog-awesome
```
3. Delete the original file `myblog\config.toml`, copy `myblog\themes\hugo-blog-awesome\exampleSite\config.toml` to the `myblog` folder.
4. **No other code changes**, directly run `hugo server`.
My blog is running successfully on http://localhost:1313 .

Look up the title of the home page,It shows `Awesome Hugo blog | Awesome Hugo blog`.
html source code:
```
<title itemprop="name">Awesome Hugo blog | Awesome Hugo blog</title>
```

**Expected behavior**
I don't think this is the correct title,the correct title should be `Home | Awesome Hugo blog`

**Comment by hugo-sid** [comment]
Can you add file `myblog/content/_index.md`, with the following content?
```
---
title: "Home"
---
```

**Comment by hugo-sid** [comment]
Take a look at:

https://github.com/hugo-sid/hugo-blog-awesome/blob/89e35ff2f71b868f6d1af2e07ddb482c53209e9c/exampleSite/content/_index.md?plain=1#L1-L4

**Comment by hugo-sid** [comment]
Hi @jerry011235.

> Thanks! Problem solved!
Happy to hear that. You're most welcome.

## Reason
Let me explain in simple terms. For every blog post, you have the frontmatter where the title is specified (shown below).

```toml
---
title = "Post title"
date = ""
# so on
---
```

For the homepage, the frontmatter is specified in `content/_index.md`.

## More info
This is related to the branch bundle concept of Hugo. You can read more about it here: https://gohugo.io/content-management/page-bundles/ .
