### ISSUE TITLE
feat: add date for page lists

### ISSUE THREAD

**Issue by kranurag78** [hugo-sid/hugo-blog-awesome#5]
Hey Sid, 
Thanks for the minimal theme. 
Can we also have dates on the page list. 
As of now we only list the title on the `/posts`

https://github.com/hugo-sid/hugo-blog-awesome/blob/f5a07184be533763b5818f462f1a87e60a97facc/layouts/_default/list.html#L15-L19

Internally I'm adding this this right next to `{{ .Title }}` 
```html
<p class="post-item-meta">{{ .Date.Format "January 2, 2006" }}</p>
```
Let me know your thoughts on this. If you're okay with this, I can push the changes.

**Comment by hugo-sid** [comment]
Hi @kranurag78 .

> Thanks for the minimal theme.

You are welcome. Thanks for using this theme.

> Can we also have dates on the page list.

I think that's a great idea.

> If you're okay with this, I can push the changes.

Feel free to submit a PR, I will be glad to merge it.
