### ISSUE TITLE
Dark theme doesn't work when using Mullvad browser (based on tor browser) with security slider at anything other than "standard"

### ISSUE THREAD

**Issue by AmyMoriyama** [hugo-sid/hugo-blog-awesome#50]
**Describe the bug**
When using the Mullvad browser (basically tor browser without the tor stuff, so this probably applies to tor browser too), the default theme is always light even when set to dark if the security slider is set to anything other than "standard".

**Steps to reproduce**
1. Get Mullvad browser: https://mullvad.net/en/download/browser/linux
2. Extract, execute
3. Set security slider to anything other than standard
4. MY EYES o_o

**Expected behavior**
I would think the security slider would have no effect on whether a site theme is dark or light.

**Screenshots**
n/a

**Device information (please complete the following information):**
cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

Mullvad browser: 12.0.6 (based on Mozilla Firefox 102.11.0esr) (64-bit)

**Additional context**
Trying to get a simple and fast website that is dark and doesn't need javascript. Which reminds me, seems javascript still is included in the public website even when configured not to be used. Of course, I am new to this whole hugo thing so could be user error.

**Comment by hugo-sid** [comment]
Thanks for reporting this bug.

I guess when the security slider is set to anything other than "standard", scripts are blocked. Can you confirm this?

**Comment by kusyka911** [comment]
As far as I know privacy oriented browsers (`brave`, `mullvad` etc.) prevent detecting system-level dark mode. And in case JS is disabled in your browser you will not be able to switch theme manually. Probably there is ability to enable dark-mode detection on browser flags page (not settings) `chrome://flags`. Or you can set dark mode by default in theme configuration.

**Comment by AmyMoriyama** [comment]
> Or you can set dark mode by default in theme configuration for your website.

I tried that. Either I changed the wrong thing or it still defaults to light theme even when set to dark. And yes, the website is meant to be loaded without javascript needed.
