### ISSUE TITLE
Use different var for meta author

### ISSUE THREAD

**Issue by mattcen** [hugo-sid/hugo-blog-awesome#68]
I see here:
https://github.com/hugo-sid/hugo-blog-awesome/blob/ef3ce2225c8d4a92f528ffd3da138edb09cf48a7/layouts/partials/meta/post.html#L39

That the JSON linked data uses `Site.Params.github` as the name of any given post's author. This means that, if this var is unset (which is likely, since the docs don't say to set it), there is no author name, and if it *is* set, it is set for *all* posts, even those which set a different author in their page metadata.

I think this should probably use per-page metadata if present, and fall back `Site.Params.author.name`. Does this seem reasonable?

**Comment by hugo-sid** [comment]
> I think this should probably use per-page metadata if present, and fall back Site.Params.author.name. Does this seem reasonable?

You are correct @mattcen. Your suggestion is wise & reasonable. I will implement this when I get some time.

**Comment by mattcen** [comment]
Depending how much it annoys me, I may also give this a shot soon. I think it'll require a custom frontmatter field because there isn't a "standard" author field but that shouldn't be a big deal.

**Comment by mattcen** [comment]
(Oh, the other thing I haven't checked is whether the linked data name field is meant to be a full name, handle, or otherwise. Will need to do that, too.)

**Comment by hugo-sid** [comment]
@mattcen, I think it makes sense to use full name for the name field.

Finally, we should have:

```html
<a href="link">Full name</a>
```

If someone wishes to use any handle (let's say twitter), they can set the parameters (in frontmatter or in site config) such that we have:

```html
<a href="https://twitter.com/handle">@handle</a>
```

**Comment by hugo-sid** [comment]
> I think it'll require a custom frontmatter field because there isn't a "standard" author field but that shouldn't be a big deal.

You are correct @mattcen.
