### ISSUE TITLE
Avatar with transparent background is always black even in light mode

### ISSUE THREAD

**Issue by poVoq** [hugo-sid/hugo-blog-awesome#92]
If you use a .png image with a transparent background as the avatar image the background is always black.

This looks good in dark-mode, but not good at all in light mode.

Would be great if that could be fixed. Thanks!

**Comment by hugo-sid** [comment]
> If you use a .png image with a transparent background as the avatar image the background is always black.

Can you provide such an image?

**Comment by poVoq** [comment]
You can see it on my current live WIP page: https://f-hub.org

**Comment by poVoq** [comment]
Would you be ok with simply removing the image background CSS part? To me it looks like this would have no negative effect, but it seems odd that it was added in the first place.

**Comment by hugo-sid** [comment]
> Would you be ok with simply removing the image background CSS part? 

Yes. That fixes this issue. Thanks.

**Comment by poVoq** [comment]
works great. thanks!
