### ISSUE TITLE
Add a _custom.sass so that people can make small css adjustments easily

### ISSUE THREAD

**Issue by poVoq** [hugo-sid/hugo-blog-awesome#93]
If you add a emtpy `_custom.sass` to the theme then people using the theme can overwrite it in their root `/assets/sass/` directory and make small css adjustments themselves.

Thanks!

**Comment by hugo-sid** [comment]
Thanks for the idea @poVoq.

I have a slightly different thought. One can [override](https://gohugo.io/templates/base/#override-the-base-template) any style sheet by creating a file with same name in `/assets/sass/` directory.

In that case do you think we need `_custom.sass` ?

**Comment by poVoq** [comment]
Yes, but then you need to copy over the entire sass file and keep track of changes you made when updating etc.

If you add an empty _custom.sass to the theme, the person overriding it has a nice self contained file that only includes the modifications and nothing else.

**Comment by hugo-sid** [comment]
Thanks for the explanation @poVoq. That makes sense.

**Comment by poVoq** [comment]
Seems to work as intended. Thanks!

**Comment by hugo-sid** [comment]
@poVoq, thanks for this idea. I plan to allow theme users to include custom HTML markup before the end of <head>
 & before the end of <body> using similar technique.
