### ISSUE TITLE
Last updated date for posts

### ISSUE THREAD

**Issue by randomodbuild** [hugo-sid/hugo-blog-awesome#95]
### Discussed in https://github.com/hugo-sid/hugo-blog-awesome/discussions/94

<div type='discussions-op-text'>

<sup>Originally posted by **randomodbuild** August  8, 2023</sup>
Just looking to add support for the lastmod entry in the frontmatter and have the last updated date also show next to the post date. </div>

**Comment by hugo-sid** [comment]
We prefer to use [discussions for feature requests](https://github.com/hugo-sid/hugo-blog-awesome/blob/main/CONTRIBUTING.md#when-to-use-issues). 

This request has already been addressed https://github.com/hugo-sid/hugo-blog-awesome/discussions/94.

**Comment by hugo-sid** [comment]
We prefer to use [discussions for feature requests](https://github.com/hugo-sid/hugo-blog-awesome/blob/main/CONTRIBUTING.md#when-to-use-issues). 

This request has already been addressed https://github.com/hugo-sid/hugo-blog-awesome/discussions/94.
